table vegtables {
    id int [pk]
    price int
    type varchar
}

table sides {
    id int [pk]
    price int
    title varchar
}

table entrees {
    id int [pk]
    price int
    name varchar
}


//should there be a total price key?
table orders {
    id int [pk]
    entreeid int [ref: > entrees.id]
    sideid int  [ref: > sides.id]
    veggieid int [ref: > vegtables.id]
}